version: '3.4'

services:
  app:
    platform: linux/x86_64
    image: webdevops/php-dev:7.4
    working_dir: /app
    container_name: app_ancor
    volumes:
      -   ./:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php

